http:
  routers:
    - rule: "PathPrefix(`/api/devices`)"
      service: device
    - rule: "PathPrefix(`/api/sessions`)"
      service: session
    - rule: "PathPrefix(`/api/assets`)"
      service: indexer
    - rule: "PathPrefix(`/api/alarms`)"
      service: alarm
    - rule: "PathPrefix(`/api/bff`)"
      service: bff
    - rule: "PathPrefix(`/health`)"
      service: bff

  services:
    device:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8101"
    session:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8102"
    indexer:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8103"
    alarm:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8104"
    bff:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8105"
